fix(policy): Fix error: undefined local variable or method `policy'
'rails server' command
fail:
/opt/zabbix-screens-generator/config/initializers/content_security_policy.rb:1:in
`<top (required)>': undefined local variable or method `policy' for
main:Object (NameError)